# Generated by Django 5.1.2 on 2024-10-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('vidname', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
