# Generated by Django 5.1.2 on 2024-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
