# Generated by Django 5.1.2 on 2024-10-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_videos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
