# Generated by Django 5.1.2 on 2024-10-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_videos_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('item', models.CharField(blank=True, max_length=200)),
                ('quan', models.IntegerField()),
            ],
        ),
    ]
