# Generated by Django 5.1.2 on 2024-10-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_inventory_quan'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quan',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
