# Generated by Django 5.1.2 on 2024-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_inventory_quan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quan',
            field=models.IntegerField(),
        ),
    ]
