# Generated by Django 5.1.2 on 2024-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_inventory_quan'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='units',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
